### PR TITLE
JDBC Named parameters

### PR DESCRIPTION
**Pull request by ckaminski**
Coupled with a pull request on vertx-jdbc-client, implements named parameters to SQL calls, for long queries. 

Can use some additional documentation - submitting to open discussion on usefulness of said feature.

### CODE REVIEW

**Comment by cescoffier** [comment]
@pmlopes  what's the status of this ?

**Comment by ckaminski** [comment]
I have to rebase to 3.1 or the 3.2-SNAPSHOT.  If there are no objections to how things were done with this version against 3.0, if you think it's worthwhile, I'll rebase to 3.2?

**Comment by pmlopes** [comment]
There are no tests. That is a blocking for the feature.

**Comment by ckaminski** [comment]
I would appreciate recommendations for testing the interfaces - there were no existing testcases for SQLConnection (java/groovy).  

Testcases exist in vertx-jdbc-client for this feature.

**Comment by pmlopes** [comment]
Yes you can add tests in the jdbc client and link to this PR so we can have at least something

**Pull request closed without merging**
