### PR TITLE
Add a get unwrapped connection

### PR DESCRIPTION
**Pull request by pmlopes**
Required by: https://github.com/vert-x3/vertx-jdbc-client/pull/94

### CODE REVIEW

**Comment by tsegismont** [comment]
Thinking about this again, a user could create the JDBCClient providing a `java.sql.Datasource`. Then for JDBC native stuff he/she would only interact with the datasource (wrapped in executeBlocking).

**Comment by pmlopes** [comment]
That would be JDBC specific, for example the async driver would not work. This is the reason I choose to propose it this way.

But it is true if one wants full control on the jdbc connection then the best would be to implement a connection pool SPI https://github.com/vert-x3/vertx-jdbc-client/blob/master/src/main/java/io/vertx/ext/jdbc/spi/DataSourceProvider.java

**Comment by vietj** [comment]
we should not call it _native_ which has a precise and different meaning

**Comment by pmlopes** [comment]
Ok, what name would you suggest? It shouldn't be related to jdbc since this is also possible to return the asynchronous client connection.

**Comment by vietj** [comment]
`rawConnection()` ?

**Comment by cescoffier** [comment]
`unwrap` ?

**Comment by pmlopes** [comment]
renamed to unwrap and updated javadoc

**Comment by tsegismont** [comment]
+1 for unwrap

2017-03-26 11:46 GMT+02:00 Clement Escoffier <notifications@github.com>:

**Pull request merged**
